### ISSUE TITLE
Bitcode bundle could not be generated error because AGConnectAppLinking was built without full bitcode

### ISSUE THREAD

**Issue by blexxed** [HMS-Core/hms-react-native-plugin#112]
**Description**
Cannot build archive in XCode.
Bitcode bundle could not be generated error because AGConnectAppLinking was built without full bitcode.

Exact error:
bitcode bundle could not be generated because '/app/ios/Pods/AGConnectAppLinking/AGConnectAppLinking.framework/AGConnectAppLinking(Pods-AGConnectAppLinking-dummy.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/app/ios/Pods/AGConnectAppLinking/AGConnectAppLinking.framework/AGConnectAppLinking' for architecture armv7

**Expected behavior**
To be able to archive

**Current behavior**
Error in archiving

**Environment**
 - Platform: ReactNative
 - Kit: App Linking
 - OS: iOS

**Comment by gbk94** [comment]
Hello, I tried to archive a react native project with AGC AppLinking plugin and got the same issue.

I found a way to fix it.

Select your target > Build Settings and search for Enable Bitcode and set to No

**Comment by gbk94** [comment]
Hello, I tried to archive a react native project with AGC AppLinking plugin and got the same issue.

I found a way to fix it. You need to disable bitcode otherwise you need to wait for plugin to support full bitcode.

Select your target > Build Settings and search for Enable Bitcode and set to No

![4C5C486E-3323-46CC-BEB6-6E433787E48F](https://user-images.githubusercontent.com/40902099/119483048-40b2cd00-bd5d-11eb-8862-448c4c3eea6a.png)
