### ISSUE TITLE
[react-native-hms-map] onCameraIdle / onCameraMoveStarted

### ISSUE THREAD

**Issue by peltax** [HMS-Core/hms-react-native-plugin#158]
**Description**
When user is dragging the map there is onCameraMoveStarted / onCameraIdle event spam in the middle of dragging. It happens most frequently when you're moving small distances or drag slowly. 

I tried to "fix" this by using counter variable that only executes onCameraIdle logic when it's 0 but sometimes it misses events or they don't fire at all and counter is -1 or 2 after touch is released. 

The only workaround that works is to update timestamp in onCameraMoveStarted and add artificial 2000ms setTimeout to onCameraIdle handler and execute logic only after delay is expired (= movement really ended).

EDIT: 2000ms is only required in dev build, ~500ms is enough in release build. This issue is maybe bug in native gesture handling in map library?

**Expected behavior**
onCameraMoveStarted is called exactly once when user starts to drag map (reason = GESTURE).
onCameraMove is called during dragging (I don't use this event currently).
onCameraIdle is called exactly once after user releases finger

**Environment**
 - Platform: react-native 0.64.2
 - Kit: Map
 - Kit Version 5.2.0-302
 - Android 10, 
 - Honor 20 lite (HMS Core version 6.2.0.301)
 - Node Version 14.17.6

**Other**
Consider adding onTouchStarted and onTouchReleased events if current behaviour is intended.

**Comment by ozcanozgur** [comment]
Hi @peltax,

According to our tests the issue is caused by the native Android Huawei Map SDK. Huawei React Native Map Plugin is a wrapper of native [Android Huawei Map](https://developer.huawei.com/consumer/en/hms/huawei-MapKit) SDK thus inherits the behaviours of it. For any question and suggestions please [submit a ticket online.](https://developer.huawei.com/consumer/en/support/feedback/#/)

Thank you for your interest.
