### ISSUE TITLE
In App Payment

### ISSUE THREAD

**Issue by UzairSoken** [HMS-Core/hms-react-native-plugin#185]
I am integrating Huawei in app payment module in my react native application, I have followed all the guidelines for setup. Every thing is going  smooth but when i try to call a method it returns error.
 ```
  HMSIapModule.isSandboxActivated()
        .then((isSandboxActivatedResult) => {
          console.log(JSON.stringify(isSandboxActivatedResult), 'result');
        })
        .catch((err) => {
          console.log(JSON.stringify(err), 'err');
        });
```

I have also implemented different methods  of this module but it gives the same error every time.
I have also searched for the status code of error in Huawei but it not giving any complete guideline  to resolve it.

**Expected behavior**
It should give success for further procceseing.

**Current behavior**
What actually happened？

**Screenshots**
[](url)

**Logs**
{"statusCode":907135000,"isSuccess":<img width="1440" alt="Screenshot 2022-04-22 at 1 25 35 PM" src="https://user-images.githubusercontent.com/97950879/164649244-cb97e86c-1445-41f0-9ed3-ed7a820867fa.png">}

**Environment**
React Native 
Android

**Comment by i01000101** [comment]
Hi @UzairSoken, 

According to our tests your issue is related to [AppGallery Connect Configuration](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides-V1/integrating-sdk-0000001050726210-V1#section1337662733318). Please make sure you put the  agconnect-services.json file in the right directory.

Also you can check this [blog](https://medium.com/huawei-developers/what-can-i-do-if-appid-and-cpid-cannot-be-found-during-an-hms-core-sdk-integration-test-3916330dcfe7).

Thank you for your interest in our plugins.
