### ISSUE TITLE
iOS builds broken with react-native-hms-analytics

### ISSUE THREAD

**Issue by Aletagro** [HMS-Core/hms-react-native-plugin#83]
**Description**
Add `@hmscore/react-native-hms-analytics` in project, add the AppGallery Connect configuration file and run the pod install command:

```
[!] Unable to determine Swift version for the following pods:

- react-native-hms-analytics does not specify a Swift version and none of the targets (`Sima`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Environment**
 - Platform: React-Native
 - Kit: Analytics
 - Kit Version: 5.1.0-300-01

**Comment by rozeridilar** [comment]
Hello, thank you for informing. Can you please delete package-lock.json and try running the project with react-native-hms-analytics -version 5.1.0-300-02?

**Comment by Aletagro** [comment]
> Hello, thank you for informing. Can you please delete package-lock.json and try running the project with react-native-hms-analytics -version 5.1.0-300-02?

Thanks for the answer. But it didn't help

**Comment by rozeridilar** [comment]
I created a new project by running following command:
`$ react-native init newproject` 
then added react-native-hms-analytics in package.json file and ran 
`$ npm install`
then directed into ios file and ran
 `$ pod install`
and everything works. Even with 5.1.0-300-01 version it was working. I think the problem is in your XCode target. Have you configured **SWIFT_VERSION** in Build Settings earlier? 
If you have implemented swift earlier in your project, Make sure you followed below statements:
- Open the project with XCode. Then choose File -> New -> File -> Swift File.
A dialog will be displayed when creating the swift file. XCode will ask you if you wish to create Bridging Header, click yes.
- Make sure you have SWIFT_VERSION 5 selected in you XCode -> Build Settings
- Go to your ios folder, delete Podfile.lock and Pods folder and then execute pod install --repo-update
- Lastly I found this [answer](https://developer.apple.com/forums/thread/6796?answerId=224652022#224652022) that may help you. If you have changed swift versions earlier, I guess creating a new empty swift file will also configure your XCode to default settings.
